respiratory:
  redis:
    host: cloud.respiratory
    password: 123456
  db:
    host: cloud.respiratory
    password: 123
  jwt:
    jks:
      password: respiratory123cloud456
      tokenTTL: 1000d
  nacos:
    host: cloud.respiratory