server:
  port: ${respiratory.service.port}
spring:
  profiles:
    active: local
  application:
    name: ${respiratory.service.name}
  main:
    # 允许循环依赖
    allow-circular-references: true
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
      discovery:
        server-addr: ${respiratory.nacos.host}:8848
        cluster-name: "FuZhou"
        namespace: 47c88cd1-8fcb-4922-ae8d-f67e979256bc
    gateway:
      routes:
        - id: disease-service
          uri: lb://disease-service
          predicates:
            - Path=/disease/**
        - id: doctor-interview-service
          uri: lb://doctor-interview-service
          predicates:
            - Path=/interview/**
        - id: drug-service
          uri: lb://drug-service
          predicates:
            - Path=/drug/**
        - id: expenses-record-service
          uri: lb://expenses-record-service
          predicates:
            - Path=/expense-record/**
        - id: family-history-service
          uri: lb://family-history-service
          predicates:
            - Path=/history/family/**
        - id: healthcare-pay-service
          uri: lb://healthcare-pay-service
          predicates:
            - Path=/healthcare/order/**
        - id: medical-provider-service
          uri: lb://medical-provider-service
          predicates:
            - Path=/medical/provider/**
        - id: medical-provider-department-service
          uri: lb://medical-provider-department-service
          predicates:
            - Path=/medical/department/**
        - id: medical-provider-form-service
          uri: lb://medical-provider-form-service
          predicates:
            - Path=/medical/form/**
        - id: medical-provider-job-service
          uri: lb://medical-provider-job-service
          predicates:
            - Path=/medical/job/**
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/patient/**
        - id: specific-using-drug-record-service
          uri: lb://specific-using-drug-record-service
          predicates:
            - Path=/special-using-drug/**
        - id: symptomatic-presentation-service
          uri: lb://symptomatic-presentation-service
          predicates:
            - Path=/symptomatic-presentation/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/** # 逗号隔开更多路径
        - id: visit-doctor-service
          uri: lb://visit-doctor-service
          predicates:
            - Path=/visit/**



knife4j:
  # 聚合swagger文档
  gateway:
    enabled: true
    # 指定手动配置的模式(默认为该模式)
    strategy: manual
    routes:
      - name: 用户服务
        url: /user/v2/api-docs
        service-name: user-service  # 服务名
      - service-name: disease-service
        url: /disease/v2/api-docs
        name: 疾病服务
      - service-name: doctor-interview-service
        url: /interview/v2/api-docs
        name: 医生问诊服务
      - service-name: drug-service
        url: /drug/v2/api-docs
        name: 药物服务
      - service-name: expenses-record-service
        url: /expense-record/v2/api-docs
        name: 费用记录服务
      - service-name: family-history-service
        url: /history/family/v2/api-docs
        name: 家族史服务
      - service-name: healthcare-pay-service
        url: /healthcare/order/v2/api-docs
        name: 医保支付服务
      - service-name: medical-provider-service
        url: /medical/provider/v2/api-docs
        name: 医疗提供者服务
      - service-name: medical-provider-department-service
        url: /medical/department/v2/api-docs
        name: 医疗提供科室服务
      - service-name: medical-provider-form-service
        url: /medical/form/v2/api-docs
        name: 医疗提供机构服务
      - service-name: medical-provider-job-service
        url: /medical/job/v2/api-docs
        name: 理疗提供者职业服务
      - service-name: patient-service
        url: /patient/v2/api-docs
        name: 病患服务
      - service-name: specific-using-drug-record-service
        url: /special-using-drug/v2/api-docs
        name: 药物具体使用服务
      - service-name: symptomatic-presentation-service
        url: /symptomatic-presentation/v2/api-docs
        name: 症状服务
      - service-name: visit-doctor-service
        url: /visit/v2/api-docs
        name: 就诊服务
dubbo:
  application:
    name: ${spring.application.name} # 需要唯一
  # 注册中心
  registry:
    address: nacos://${spring.cloud.nacos.discovery.server-addr}
  # 包扫描
  scan:
    base-packages: ${respiratory.service.dubbo.web-earn-scan}
# jwt配置
respiratory:
  jwt:
    location: classpath:respiratory-cloud.jks
    alias: respiratory
    password: ${respiratory.jwt.jks.password} # 解析文件的密钥(文件本身也是密钥)
    tokenTTL: ${respiratory.jwt.jks.tokenTTL}
  auth:
    include-paths:
      - "/user/logout"
      - "/user/me"
      - "/user/update"
      - "/user/create"
      - "/upload/respiratory/**"
    root-auth-paths:
      - "/user/create"
  service:
    port: 8080
    name: gateway
    scan:
      controller: org.harvey.respiratory.cloud.gateway.interceptor
    doc:
      name: ${respiratory.service.name}
      description: 网关
    dao:
      database: cr_placeholder # 占位, 由于此服务无数据库
    dubbo:
      web-earn-scan: ${respiratory.service.scan.controller}
