respiratory:
  db:
    host: mysql
    password: 123
  redis:
    host: redis
    password: 123456
  es:
    host: es
    port: 9200
  identity-card:
    open-code-verify: true
    city-sorted: service-role\src\main\resources\address_on_id.json
  nacos:
    host: nacos