server:
  port: ${respiratory.service.port}
  servlet:
    context-path: ${respiratory.service.base.url}
spring:
  profiles:
    active: local
  application:
    name: ${respiratory.service.name}
  main:
    # 允许循环依赖
    allow-circular-references: true
  cloud:
    nacos:
      server-addr: ${respiratory.nacos.host}:8848
      discovery:
        cluster-name: "FuZhou"
        namespace: 47c88cd1-8fcb-4922-ae8d-f67e979256bc
dubbo:
  application:
    name: dubbo-${spring.application.name} # 需要唯一
    parameters[namespace]: ${spring.cloud.nacos.discovery.namespace}
    parameters[group]: DUBBO
  # 注册中心
  registry:
    address: nacos://${spring.cloud.nacos.server-addr}
  # 包扫描
  scan:
    base-packages:
      - ${respiratory.service.dubbo.web-earn-scan}
      - ${respiratory.service.dubbo.service-impl-scan}
  protocol:
    name: dubbo
    port: -1

respiratory:
  service:
    port: 8090
    name: healthcare-pay-service
    base:
      url: /healthcare/order
      package: org.harvey.respiratory.cloud.hp.server
    scan:
      controller: ${respiratory.service.base.package}.controller
      service-impl: ${respiratory.service.base.package}.service.impl
    doc:
      name: ${respiratory.service.name}
      description: 医保支付服务
    dao:
      database: cr_placeholder
    dubbo:
      service-impl-scan: ${respiratory.service.scan.service-impl}
      web-earn-scan: ${respiratory.service.scan.controller}
